// GENERATED by tool/apply_brand.dart — do not edit by hand.
// Values are derived from brands/<brand>/firebase/google-services.json and
// GoogleService-Info.plist (the single Firebase source per brand).
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return android;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return ios;
      case TargetPlatform.windows:
        return android;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZk747HCaMuxl_91A0Ww1U5rGRGYsCaNU',
    appId: '1:170394280458:android:9dcf8e5f53ef082d0835f3',
    messagingSenderId: '170394280458',
    projectId: 'madrasmilk-1f52e',
    storageBucket: 'madrasmilk-1f52e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOHRj8_wvLAHlLUvVQuNttUVDKoi0ajcs',
    appId: '1:170394280458:ios:aa9a12e82d085d3d0835f3',
    messagingSenderId: '170394280458',
    projectId: 'madrasmilk-1f52e',
    storageBucket: 'madrasmilk-1f52e.firebasestorage.app',
    iosBundleId: 'com.aaraakart.madrasmilk',
  );
}
